# Import all models so they register with SQLAlchemy
from .user import User
from .serre import Serre
from .domaine import Domaine
from .bilan import Bilan
from .autorisation_serre import Autorisation_serre
from .guide_culture import GuideCulture
from .points_gps import GroupCor
from .entreprise import Entreprise
from .rapport import Rapport
from .notification import Notification
from .mission_robot import MissionRobot
from .etat_bilan import Etat_bilan
from .alerte import Alerte
from .type_tache import TypeTache
from .robot import Robot
from .intervention import Intervention
from .autorisation_domaine import Autorisation_domaine
from .autorisation_bilan import Autorisation_bilan
