/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TechMapRouteRouteImport } from './routes/tech-map-route'
import { Route as SetUpPageGMapsRouteImport } from './routes/setUpPageGMaps'
import { Route as RegistrationRouteRouteImport } from './routes/registration-route'
import { Route as NewInscriptionDirecteurRouteImport } from './routes/new-inscription-directeur'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as InscriptionTechnicienRouteImport } from './routes/inscription-technicien'
import { Route as InscriptionDirecteurRouteImport } from './routes/inscription-directeur'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as BilansRouteImport } from './routes/bilans'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AlertheatmapRouteImport } from './routes/alertheatmap'
import { Route as IndexRouteImport } from './routes/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TechMapRouteRoute = TechMapRouteRouteImport.update({
  id: '/tech-map-route',
  path: '/tech-map-route',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUpPageGMapsRoute = SetUpPageGMapsRouteImport.update({
  id: '/setUpPageGMaps',
  path: '/setUpPageGMaps',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRouteRoute = RegistrationRouteRouteImport.update({
  id: '/registration-route',
  path: '/registration-route',
  getParentRoute: () => rootRouteImport,
} as any)
const NewInscriptionDirecteurRoute = NewInscriptionDirecteurRouteImport.update({
  id: '/new-inscription-directeur',
  path: '/new-inscription-directeur',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionTechnicienRoute = InscriptionTechnicienRouteImport.update({
  id: '/inscription-technicien',
  path: '/inscription-technicien',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionDirecteurRoute = InscriptionDirecteurRouteImport.update({
  id: '/inscription-directeur',
  path: '/inscription-directeur',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const BilansRoute = BilansRouteImport.update({
  id: '/bilans',
  path: '/bilans',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertheatmapRoute = AlertheatmapRouteImport.update({
  id: '/alertheatmap',
  path: '/alertheatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertheatmap': typeof AlertheatmapRoute
  '/alerts': typeof AlertsRoute
  '/bilans': typeof BilansRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription-directeur': typeof InscriptionDirecteurRoute
  '/inscription-technicien': typeof InscriptionTechnicienRoute
  '/interventions': typeof InterventionsRoute
  '/login': typeof LoginRoute
  '/new-inscription-directeur': typeof NewInscriptionDirecteurRoute
  '/registration-route': typeof RegistrationRouteRoute
  '/setUpPageGMaps': typeof SetUpPageGMapsRoute
  '/tech-map-route': typeof TechMapRouteRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertheatmap': typeof AlertheatmapRoute
  '/alerts': typeof AlertsRoute
  '/bilans': typeof BilansRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription-directeur': typeof InscriptionDirecteurRoute
  '/inscription-technicien': typeof InscriptionTechnicienRoute
  '/interventions': typeof InterventionsRoute
  '/login': typeof LoginRoute
  '/new-inscription-directeur': typeof NewInscriptionDirecteurRoute
  '/registration-route': typeof RegistrationRouteRoute
  '/setUpPageGMaps': typeof SetUpPageGMapsRoute
  '/tech-map-route': typeof TechMapRouteRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertheatmap': typeof AlertheatmapRoute
  '/alerts': typeof AlertsRoute
  '/bilans': typeof BilansRoute
  '/connexion': typeof ConnexionRoute
  '/dashboard': typeof DashboardRoute
  '/inscription-directeur': typeof InscriptionDirecteurRoute
  '/inscription-technicien': typeof InscriptionTechnicienRoute
  '/interventions': typeof InterventionsRoute
  '/login': typeof LoginRoute
  '/new-inscription-directeur': typeof NewInscriptionDirecteurRoute
  '/registration-route': typeof RegistrationRouteRoute
  '/setUpPageGMaps': typeof SetUpPageGMapsRoute
  '/tech-map-route': typeof TechMapRouteRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertheatmap'
    | '/alerts'
    | '/bilans'
    | '/connexion'
    | '/dashboard'
    | '/inscription-directeur'
    | '/inscription-technicien'
    | '/interventions'
    | '/login'
    | '/new-inscription-directeur'
    | '/registration-route'
    | '/setUpPageGMaps'
    | '/tech-map-route'
    | '/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertheatmap'
    | '/alerts'
    | '/bilans'
    | '/connexion'
    | '/dashboard'
    | '/inscription-directeur'
    | '/inscription-technicien'
    | '/interventions'
    | '/login'
    | '/new-inscription-directeur'
    | '/registration-route'
    | '/setUpPageGMaps'
    | '/tech-map-route'
    | '/verify-email'
  id:
    | '__root__'
    | '/'
    | '/alertheatmap'
    | '/alerts'
    | '/bilans'
    | '/connexion'
    | '/dashboard'
    | '/inscription-directeur'
    | '/inscription-technicien'
    | '/interventions'
    | '/login'
    | '/new-inscription-directeur'
    | '/registration-route'
    | '/setUpPageGMaps'
    | '/tech-map-route'
    | '/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertheatmapRoute: typeof AlertheatmapRoute
  AlertsRoute: typeof AlertsRoute
  BilansRoute: typeof BilansRoute
  ConnexionRoute: typeof ConnexionRoute
  DashboardRoute: typeof DashboardRoute
  InscriptionDirecteurRoute: typeof InscriptionDirecteurRoute
  InscriptionTechnicienRoute: typeof InscriptionTechnicienRoute
  InterventionsRoute: typeof InterventionsRoute
  LoginRoute: typeof LoginRoute
  NewInscriptionDirecteurRoute: typeof NewInscriptionDirecteurRoute
  RegistrationRouteRoute: typeof RegistrationRouteRoute
  SetUpPageGMapsRoute: typeof SetUpPageGMapsRoute
  TechMapRouteRoute: typeof TechMapRouteRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-map-route': {
      id: '/tech-map-route'
      path: '/tech-map-route'
      fullPath: '/tech-map-route'
      preLoaderRoute: typeof TechMapRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setUpPageGMaps': {
      id: '/setUpPageGMaps'
      path: '/setUpPageGMaps'
      fullPath: '/setUpPageGMaps'
      preLoaderRoute: typeof SetUpPageGMapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-route': {
      id: '/registration-route'
      path: '/registration-route'
      fullPath: '/registration-route'
      preLoaderRoute: typeof RegistrationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-inscription-directeur': {
      id: '/new-inscription-directeur'
      path: '/new-inscription-directeur'
      fullPath: '/new-inscription-directeur'
      preLoaderRoute: typeof NewInscriptionDirecteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-technicien': {
      id: '/inscription-technicien'
      path: '/inscription-technicien'
      fullPath: '/inscription-technicien'
      preLoaderRoute: typeof InscriptionTechnicienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription-directeur': {
      id: '/inscription-directeur'
      path: '/inscription-directeur'
      fullPath: '/inscription-directeur'
      preLoaderRoute: typeof InscriptionDirecteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilans': {
      id: '/bilans'
      path: '/bilans'
      fullPath: '/bilans'
      preLoaderRoute: typeof BilansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertheatmap': {
      id: '/alertheatmap'
      path: '/alertheatmap'
      fullPath: '/alertheatmap'
      preLoaderRoute: typeof AlertheatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertheatmapRoute: AlertheatmapRoute,
  AlertsRoute: AlertsRoute,
  BilansRoute: BilansRoute,
  ConnexionRoute: ConnexionRoute,
  DashboardRoute: DashboardRoute,
  InscriptionDirecteurRoute: InscriptionDirecteurRoute,
  InscriptionTechnicienRoute: InscriptionTechnicienRoute,
  InterventionsRoute: InterventionsRoute,
  LoginRoute: LoginRoute,
  NewInscriptionDirecteurRoute: NewInscriptionDirecteurRoute,
  RegistrationRouteRoute: RegistrationRouteRoute,
  SetUpPageGMapsRoute: SetUpPageGMapsRoute,
  TechMapRouteRoute: TechMapRouteRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
