/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechMapRouteRouteImport } from './routes/tech-map-route'
import { Route as RegistrationRouteRouteImport } from './routes/registration-route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const TechMapRouteRoute = TechMapRouteRouteImport.update({
  id: '/tech-map-route',
  path: '/tech-map-route',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRouteRoute = RegistrationRouteRouteImport.update({
  id: '/registration-route',
  path: '/registration-route',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/interventions': typeof InterventionsRoute
  '/login': typeof LoginRoute
  '/registration-route': typeof RegistrationRouteRoute
  '/tech-map-route': typeof TechMapRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/interventions': typeof InterventionsRoute
  '/login': typeof LoginRoute
  '/registration-route': typeof RegistrationRouteRoute
  '/tech-map-route': typeof TechMapRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/interventions': typeof InterventionsRoute
  '/login': typeof LoginRoute
  '/registration-route': typeof RegistrationRouteRoute
  '/tech-map-route': typeof TechMapRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/interventions'
    | '/login'
    | '/registration-route'
    | '/tech-map-route'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/interventions'
    | '/login'
    | '/registration-route'
    | '/tech-map-route'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/interventions'
    | '/login'
    | '/registration-route'
    | '/tech-map-route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DashboardRoute: typeof DashboardRoute
  InterventionsRoute: typeof InterventionsRoute
  LoginRoute: typeof LoginRoute
  RegistrationRouteRoute: typeof RegistrationRouteRoute
  TechMapRouteRoute: typeof TechMapRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tech-map-route': {
      id: '/tech-map-route'
      path: '/tech-map-route'
      fullPath: '/tech-map-route'
      preLoaderRoute: typeof TechMapRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-route': {
      id: '/registration-route'
      path: '/registration-route'
      fullPath: '/registration-route'
      preLoaderRoute: typeof RegistrationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DashboardRoute: DashboardRoute,
  InterventionsRoute: InterventionsRoute,
  LoginRoute: LoginRoute,
  RegistrationRouteRoute: RegistrationRouteRoute,
  TechMapRouteRoute: TechMapRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
